In [2]:
#  Add a scalar to an array

import numpy as np
a = np.array([1, 2, 3])
result = a + 5  # Each element gets 5 added
print(result)

[6 7 8]


In [3]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
bias = np.array([1, 1, 1])
result = matrix + bias
print(result)

[[2 3 4]
 [5 6 7]]


In [4]:
data = np.array([[10, 20, 30], [5, 15, 25]])
row_means = data.mean(axis=1, keepdims=True)
normalized = data - row_means
print(normalized)

[[-10.   0.  10.]
 [-10.   0.  10.]]


Exercise 1: Sales Boost
You have a daily sales array. Add a 10% commission bonus using broadcasting.

In [6]:
import numpy as np

# Daily sales for a week (Monday to Sunday)
daily_sales = np.array([1200, 1350, 990, 1450, 1600, 1800, 2000])

#  multiply the array by 1.10 to add 10%.
sales_with_bonus = daily_sales * 1.10

print(f"Sales after adding 10% commission are:{sales_with_bonus}")

Sales after adding 10% commission are:[1320. 1485. 1089. 1595. 1760. 1980. 2200.]


Exercise 2: Normalize Data
Given a 2D matrix of student scores, subtract the mean score of each student (row-wise normalization).

In [8]:
import numpy as np

scores = np.array([
    #math,sci,eng
    [78, 85, 90], #student 1
    [92, 88, 84], #student 2
    [70, 75, 80], #student 3
    [88, 94, 90] #student 4
])

#mean of each row
row_means = scores.mean(axis=1)
print(row_means)

# normalizing each row by substracting its mean
normalised_score = np.mean(scores, axis=1, keepdims=True)

print(normalised_score)



[84.33333333 88.         75.         90.66666667]
[[84.33333333]
 [88.        ]
 [75.        ]
 [90.66666667]]


Exercise 3: Image Simulation
Simulate a grayscale image (3x3 matrix). Increase brightness using a scalar and add a “filter” (another matrix) using broadcasting.

In [9]:
import numpy as np

#dummy data
image = np.array([
    [120, 130, 140],
    [150, 160, 170],
    [180, 190, 200]
])

# brightness
brightness = 50

# filter to apply (vertical boost)
filter_matrix = np.array([
    [10],
    [20],
    [30]
])

# increase brightness
brightened_image = image + brightness

# filter using broadcasting
filtered_image = brightened_image + filter_matrix

# Print final result
print("Filtered Image:")
print(filtered_image)


Filtered Image:
[[180 190 200]
 [220 230 240]
 [260 270 280]]
