indexing

In [1]:
import numpy as np

study_hours = np.array([6,2,5,2,4,3,7])

In [2]:
print(study_hours[0])
print(study_hours[-1])
print(study_hours[-5])
print(study_hours[-2])

6
7
5
3


slicing

In [3]:
import numpy as np

study_hours = np.array([6,2,5,2,4,3,7])

In [6]:
print(study_hours[1:-2])

print(study_hours[0:3]) #day 1 to day 3

[2 5 2 4]
[6 2 5]


filtering

In [7]:
print(study_hours[study_hours > 2])

[6 5 4 3 7]


Exercise 3:

Print your study hours for the weekend (assume last 2 days).

Print days where you studied more than 4 hours.

Calculate average score only for days where score > 40.

In [13]:
learning_time = np.array([7, 6, 4])
print(learning_time)

print(f"days i learned more than 4 hours are:{learning_time[learning_time > 4]}")

productivity_score = learning_time * 10
average_productivity_score = productivity_score.mean()
print(f"The average productivity score is {average_productivity_score:.2f}")

[7 6 4]
days i learned more than 4 hours are:[7 6]
The average productivity score is 56.67


Top 3 productivity scores

Day(s) with score above weekly average

In [15]:
print(productivity_score)
print(productivity_score[average_productivity_score < productivity_score])

[70 60 40]
[70 60]
