A 2D NumPy array is like a table — rows and columns of numbers.
Shape looks like (rows, columns)

In [3]:
import numpy as np

scores = np.array([
# Math, Science, English
    [85, 90, 88],  # (Student 1)
    [78, 80, 75],  # Student 2
    [92, 88, 95]   # Student 3
])
print(scores)

[[85 90 88]
 [78 80 75]
 [92 88 95]]


In [5]:
print(scores.shape)        # (3, 3)
print(scores.ndim)          # 2 dimensions
print(scores[0])            # First row (Student 1)
print(scores[:, 0])         # First column (Math scores)
print(scores[1, 2])         # Row 1, Col 2 → Student 2's English
print(scores.mean(axis=0))  # Average of each column (subject)
print(scores.mean(axis=1))  # Average of each row (student)


(3, 3)
2
[85 90 88]
[85 78 92]
75
[85. 86. 86.]
[87.66666667 77.66666667 91.66666667]


Create a 2D array of 4 students and 3 subjects

Print:

Shape and dimension

All Science scores

Highest score in English

Average score of each student

Average score for each subject

In [ ]:
marks = np.array([
#eng, science, math
    [45, 55, 65],
    [56, 98, 78],
    [89, 67, 81]
])
print(marks)
print(marks.shape)
print(marks.ndim)
print(marks[:,1])
print(marks[:,0].max())
print(marks.mean(axis=0))
print(marks.mean(axis=1))


print()

[[45 55 65]
 [56 98 78]
 [89 67 81]]
(3, 3)
2
[55 98 67]
89
[63.33333333 73.33333333 74.66666667]
[55.         77.33333333 79.        ]


In [16]:
import numpy as np

# Student scores: [English, Science, Math]
marks = np.array([
    [45, 55, 65],   # Student 1
    [56, 98, 78],   # Student 2
    [89, 67, 81]    # Student 3
])

# Average score per student (row-wise)
student_avg = marks.mean(axis=1)
print(f"Average score per student: {student_avg}")

# Average score per subject (column-wise)
subject_avg = marks.mean(axis=0)
print(f"Average score per subject: {subject_avg}")

# Best performing student (highest average)
best_student_index = student_avg.argmax()
print(f"Best performing student is Student {best_student_index + 1} with average {student_avg[best_student_index]:.2f}")

# Weakest subject (lowest average)
weakest_subject_index = subject_avg.argmin()
subjects = ['English', 'Science', 'Math']
print(f"Weakest subject is {subjects[weakest_subject_index]} with average {subject_avg[weakest_subject_index]:.2f}")


Average score per student: [55.         77.33333333 79.        ]
Average score per subject: [63.33333333 73.33333333 74.66666667]
Best performing student is Student 3 with average 79.00
Weakest subject is English with average 63.33
