Broadcasting allows numpy to perform operation on arrays of different shapes without writing loops.

In [2]:
#SYNTAX
#Scalar Broadcasting = 1D array + number 

#data of money saved in each day of the first week in the month of may

import numpy as np 

money_saved = np.array([100,150,200,250,300,350,400])

"""
    Initially above data was the idea to save money but I have been saving 50 rupees more than the initial plan
    """

adjusted_saving = money_saved + 50

print(f"Money I saved in each day of the first week of the May is:{adjusted_saving}")

Money I saved in each day of the first week of the May is:[150 200 250 300 350 400 450]


In [16]:
#SYNTAX
# Vector Broadcasting = 2D + 1D 

scores = np.array([
    #eng,nep,math
    [60,60,65],  #student 1
    [65,68,62],  #student 2
    [70,60,68]   #student 3
])

"""
This is the marks of the # subjects English, Nepali and Math in which I forgot to add Practical marks so Now I will add 25 to each subjects of each students
    """
practical_scores = np.array([25,25,25])

new_scores = scores + practical_scores

print(f"The Marks of the students including theory Practical scores is\n:{new_scores}")

#Normalizing Test Scores

max_per_subject = scores.max(axis=0)

normalized_scores = (scores / max_per_subject * 100)

print(f"The Normalized scores is\n:{normalized_scores}")

The Marks of the students including theory Practical scores is
:[[85 85 90]
 [90 93 87]
 [95 85 93]]
The Normalized scores is
:[[ 85.71428571  88.23529412  95.58823529]
 [ 92.85714286 100.          91.17647059]
 [100.          88.23529412 100.        ]]


Exercise 6

Add 1 hour extra to every day — use broadcasting (no loops).

Add bonus hours: [0, 0.5, 1, 0.5, 0] — one for each day.

Calculate total hours per student using .sum(axis=1)

Print who studied the most.

In [32]:
study_data = np.array([
    [1, 2, 3, 2, 1],
    [2, 3, 4, 3, 2],
    [3, 4, 5, 4, 3]
])
#adding extra 1 hour
extra = study_data + 1

print(f"The study data after adding 1 in each data is \n{extra}\n")

#creating bonus hours array to add in the study data
bonus_hours = np.array([0, 0.5, 1, 0.5, 0])

#adding bonus hours and new study data
new_study_data = bonus_hours + study_data

print(f"The amount of hours each student studied after adding bonus hours is \n{new_study_data}\n")

#calculating total hour student studied
TotalHourPerStudent = new_study_data.sum(axis=1)

print(f"The total time each students take to study is {TotalHourPerStudent}\n")

#printing the student who studied the maximum hours
print(f"The student who studied maximum hour is one who studied {TotalHourPerStudent.max()} hours")

The study data after adding 1 in each data is 
[[2 3 4 3 2]
 [3 4 5 4 3]
 [4 5 6 5 4]]

The amount of hours each student studied after adding bonus hours is 
[[1.  2.5 4.  2.5 1. ]
 [2.  3.5 5.  3.5 2. ]
 [3.  4.5 6.  4.5 3. ]]

The total time each students take to study is [11. 16. 21.]

The student who studied maximum hour is one who studied 21.0 hours
