In [ ]:
import numpy as np

temperature = np.array([35, 34, 36, 40, 42])  #highest temperature recorded in the last 5 days

mask = temperature > 35

print(mask) #checking if temperature is higher than 35 or not

print(temperature[mask]) #temperature higher than 35

[False False  True  True  True]
[36 40 42]


In [ ]:
cond = np.where(temperature <= 35, 'Low','High') #this code prints temperature less or equal to 35 as Low but high to more than that 
print(cond)

['Low' 'Low' 'High' 'High' 'High']


In [10]:
temperature2 = np.array([21,24,26,27,30]) #temperature of random 5 days from past winter

cool_days = temperature2 < 25

print(cool_days)

print(f"Coolest days in the last winter are {temperature2[cool_days]}")

[ True  True False False False]
Coolest days in the last winter are [21 24]


In [11]:
import numpy as np

#array of daily productivity scores (out of 100) of one week
scores = np.array([45, 80, 60, 30, 90, 50, 25])


Print the days where score is below 50

Replace scores < 50 with 0 (use np.where())

Calculate the new average productivity

Print how many days were poor productivity days (score < 50)

In [22]:
mask = scores < 50

#gives boolean result of the condition inside of the array
print(mask)

#fetch the result from the array according to the condition 
print(scores[mask])

poor_productivity = np.where(scores < 50, 'Poor', 'Good')

print(poor_productivity)

adjusted_scores = np.where(scores < 50, 0,scores)

print(adjusted_scores)

#gives out average productivity throughout the week
print(scores.mean())

# #count days where  productivity were poor
poor_days = mask.sum()
print(poor_days)



[ True False False  True False False  True]
[45 30 25]
['Poor' 'Good' 'Good' 'Poor' 'Good' 'Good' 'Poor']
[ 0 80 60  0 90 50  0]
54.285714285714285
3
