Sorting, Ranking and Top-N Selection in Numpy is organizing and filtering arrays based on values

In [ ]:
import numpy as np



gold_prices = np.array([180000, 220986, 210471.5, 95800, 168500, 148700])

#sorting the prices from ascending to descending order

sorted_price = np.sort(gold_prices)

print(f"The sorted Prices of gold are:{sorted_price}")

The sorted Prices of gold are:[ 95800.  148700.  168500.  180000.  210471.5 220986. ]


Argsort (Get indices of the sorted array)

In [ ]:
sorted_price = np.argsort(gold_prices) # it gives the indices of the sorted arrays

print(sorted_price) #print indices

[3 5 4 0 2 1]


Top-N values = It gives the top values from first element to n-element

In [7]:
top3_high_price = np.sort(gold_prices)[-3:]
#it print the top 3 highest valuse from the array named gold_prices
print(top3_high_price)

[180000.  210471.5 220986. ]


In [20]:
import numpy as np

# bitcoin price from year 2020 to 2021
bitcoin_prices = np.array([
    [2020, 2021, 2022, 2023, 2024],
    [28924, 46206, 16547, 42165, 42500]
])
sort_bitcoin = np.sort(bitcoin_prices)

#it gives the result of sorted array of 2D
print(np.sort(bitcoin_prices, axis = 1))


[[ 2020  2021  2022  2023  2024]
 [16547 28924 42165 42500 46206]]


In [23]:
sales_today = np.array([810, 900, 500, 200, 300, 1350, 25, 75, 50, 150])

print(sales_today)

top3_SalesToday = np.sort(sales_today)[-3:]

print(f"The top 3 sales happen today are: {top3_SalesToday}")

[ 810  900  500  200  300 1350   25   75   50  150]
The top 3 sales happen today are: [ 810  900 1350]


Exercise 1: Basic Sorting 

You are given a list of test scores:

scores = np.array([88, 95, 70, 100, 60])

Sort the scores in ascending order

Find the highest 3 scores

Print their original indices (use np.argsort())

In [ ]:
# exercise 1
import numpy as np
scores = np.array([88, 95, 70, 100, 60])

sorted_score = np.sort(scores) # it will sort the array in ascending order 

print(sorted_score) # print sorted array 

top3 = np.sort(scores)[-3:] # it gives top 3 scores 

print(f"The top 3 Highest scores are: {top3}")

index_sort = np.argsort(scores)

print(index_sort) #gives the indices of the array after sorting

[ 60  70  88  95 100]
The top 3 Highest scores are: [ 88  95 100]
[4 2 0 1 3]


 Exercise 2: 2D Matrix Sorting

 You have this study log:

study_log = np.array([
    [3, 2, 1],
    [6, 4, 5],
    [2, 3, 2]
])

Sort each row of the matrix

Sort each column

Print top study day (highest value) per student

In [ ]:
# exercise 2
study_log = np.array([
    [3, 2, 1],
    [6, 4, 5],
    [2, 3, 2]
])

print(np.sort(study_log, axis = 1),"\n") #Sort each row of the matrix

print(np.sort(study_log, axis = 0),"\n") #Sort each column

print(study_log.max()) #Print top study day (highest value) per student


[[1 2 3]
 [4 5 6]
 [2 2 3]] 

[[2 2 1]
 [3 3 2]
 [6 4 5]] 

6


Exercise 3: Real-World Application (Sales)

sales = np.array([100, 300, 50, 450, 600, 90])

Get top 3 sales days

Show their original positions

Replace the lowest sale with the average of top 3

In [46]:
# exercise 3

sales = np.array([100, 300, 50, 450, 600, 90])

top3_sales = np.sort(sales)[-3:] # Get top 3 sales days

print(f"The top 3 sales of today are: {top3_sales}\n")

index_sorting = np.argsort(sales) #  gives their original indices

print(f"The original indices are: {index_sorting}\n")

average_top3 = top3_sales.mean()

print(f"Average sales from the top 3 is  {average_top3}\n") # gives average from top 3 sales 

minimum_sales = sales.min()

print(f"The minimum sales fot the day is {minimum_sales}\n") # gives the minimum sales from the array

sales_modify = sales.copy()

minimum_index = np.argmin(sales)

sales_modify[minimum_index] = average_top3

print(f"After replacing the lowest sales with average sales of top 3 {sales_modify}")

The top 3 sales of today are: [300 450 600]

The original indices are: [2 5 0 1 3 4]

Average sales from the top 3 is  450.0

The minimum sales fot the day is 50

After replacing the lowest sales with average sales of top 3 [100 300 450 450 600  90]
