Statistical Functions in NumPy helps to analyze and summarize data efficiently.

In [2]:
import numpy as np

# data of people death rate of each year from 2019 to 2024

death_rate = np.array([10, 20, 60, 40, 50])

print("Mean:",np.mean(death_rate))
print("Median:",np.median(death_rate))
print("Standard Deviation:",np.std(death_rate))
print("Variance:",np.var(death_rate))
print("Min:",np.min(death_rate))
print("Max:",np.max(death_rate))
print("90th Percentile:",np.percentile(death_rate, 90))



Mean: 36.0
Median: 40.0
Standard Deviation: 18.547236990991408
Variance: 344.0
Min: 10
Max: 60
90th Percentile: 56.0


salaries = np.array([40000, 55000, 60000, 75000, 50000, 95000, 120000])
# 1. Calculate mean, median, std, and variance
# 2. Find salaries above average
# 3. Replace salaries below median with median

In [11]:
# analyze salaries

salaries = np.array([40000, 55000, 60000, 75000, 50000, 95000, 120000])

# calculate mean, median, std and variance

mean_salaries = np.mean(salaries)
print(f"Mean:{mean_salaries:.2f}\n")

median_salary = np.median(salaries)
print(f"Median:{median_salary:.2f}\n")

salary_std = np.std(salaries)
print(f"Standard Deviation: {salary_std:.2f}\n")

salary_variance = np.var(salaries)
print(f"Variance: {salary_variance:.2f}\n")

# printing salaries above the average
above_avg = salaries[salaries > mean_salaries]
print(f"Salaries above average are: {above_avg}\n")

# replacing salaries below median with the median value

salaries_modify = salaries.copy()

salaries_modify = np.where(salaries < median_salary,median_salary, salaries)
print(f"After replacing salaries lower than median with median value we get: {salaries_modify}")

Mean:70714.29

Median:60000.00

Standard Deviation: 26108.10

Variance: 681632653.06

Salaries above average are: [ 75000  95000 120000]

After replacing salaries lower than median with median value we get: [ 60000.  60000.  60000.  75000.  60000.  95000. 120000.]


 Exercise 2: Student Test Scores
 
scores = np.array([
    [65, 70, 75],
    [90, 85, 88],
    [55, 60, 58],
    [95, 92, 98]
])
# 1. Compute average score per student
# 2. Compute standard deviation for each student
# 3. Identify students with variance > 50

In [46]:
scores = np.array([
    [65, 70, 75],
    [90, 85, 88],
    [55, 60, 58],
    [95, 92, 98]
])
print(scores,"\n")

# average score per student
avg_score = scores.mean(axis=1)
print(f"Average scores per student are: {avg_score}\n")

# standard deviation for each student
std_score = scores.std(axis=1)
print(f"Standard Deviation of ecery students scores are: {std_score}\n")

var_score = np.var(scores)
# students with variance > 50
high_variance_students = scores[var_score > 50]
print("Students with variance > 50:")
print(high_variance_students)

[[65 70 75]
 [90 85 88]
 [55 60 58]
 [95 92 98]] 

Average scores per student are: [70.         87.66666667 57.66666667 95.        ]

Standard Deviation of ecery students scores are: [4.0824829  2.05480467 2.05480467 2.44948974]

Students with variance > 50:
[[[65 70 75]
  [90 85 88]
  [55 60 58]
  [95 92 98]]]


 Exercise 3: App Ratings

ratings = np.array([4.5, 4.8, 4.2, 3.9, 4.0, 4.1, 4.9, 3.5, 4.7])
# 1. Find mean, median, and 75th percentile
# 2. Identify ratings below average
# 3. Replace the lowest rating with average of top 3

In [48]:
ratings = np.array([4.5, 4.8, 4.2, 3.9, 4.0, 4.1, 4.9, 3.5, 4.7])

# average rating
average_rating = np.mean(ratings)
print(f"The average rating this app got is: {average_rating:.1f}")

# median of rating
rating_median = np.median(ratings)
print(f"Median of the rating is: {rating_median}")

# 75th percentile
percentile = np.percentile(ratings, 75)
print(f"75th percentile of the rating is: {percentile}")

# rating below average
below_average = ratings[ratings < average_rating]
print(f"Rating below average are: {below_average}")

#  replacing the lowest rating with average of top 3
top3 = np.sort(ratings)[-3:]
print(f"The top three rating this app has go are: {top3}")
avg_top3 = np.mean(top3)
print(f'Average of top3 is {avg_top3}')

rating_modify = ratings.copy()
min_index = np.argmin(ratings)
rating_modify[min_index] = avg_top3
print(f"after replacing lowest rating with average of top 3 we get: {rating_modify}")


The average rating this app got is: 4.3
Median of the rating is: 4.2
75th percentile of the rating is: 4.7
Rating below average are: [4.2 3.9 4.  4.1 3.5]
The top three rating this app has go are: [4.7 4.8 4.9]
Average of top3 is 4.8
after replacing lowest rating with average of top 3 we get: [4.5 4.8 4.2 3.9 4.  4.1 4.9 4.8 4.7]
