#Exercise 1: Matrix Multiplication

#Create two 2x2 matrices and

#Multiply them using both @ and np.dot

#Transpose one matrix before multiplying

In [ ]:
#exercise 1
import numpy as np

A = np.array([[2, 4, 1],
              [0, 3, 5]])

B = np.array([[1, 2],
              [0, -1],
              [4, 3]])

# np.dot(A,B)

# A @ B

print(A.T)

np.dot(A.T,B)

[[2 0]
 [4 3]
 [1 5]]


ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

#Exercise 2: Identity Matrix and Inverse

#Create a 3x3 matrix

#Find its inverse using np.linalg.inv()

#Verify the result by multiplying the matrix with its inverse — it should return an identity matrix.

In [ ]:
#exercise 2
M = np.array([[7, 2, -1],
              [0, 3, 5],
              [4, -2, 6]])

I = np.eye(3)

M_inv = np.linalg.inv(M)

print(M_inv)

result = M @ M_inv

np.allclose(result, I)



[[ 0.11290323 -0.04032258  0.05241935]
 [ 0.08064516  0.18548387 -0.14112903]
 [-0.0483871   0.08870968  0.08467742]]


True

#Exercise 3: Dot Product in Practice

#Simulate a small dataset:

#Create a 2D array X of 3 samples with 2 features

#Create a weight array W

#Calculate the prediction using dot product

In [ ]:
#exercise 3
import numpy as np

X = np.array([[1.2, 3.4],
              [0.5, -1.3],
              [4.8, 2.2]])

W = np.array([[0.7],
              [-1.2]])

print(X @ W)

[[-3.24]
 [ 1.91]
 [ 0.72]]
