Top Performer Dashboard

given an array of weekly productivity scores for 5 users:

Tasks:

Compute the average score per user

Identify the top 2 performers

Highlight the weakest performing user

Replace the lowest average with the mean of the top 2 performers

In [23]:
# Top Performer Dashboard
import numpy as np

users = np.array([
    [70, 60, 90, 100, 85],  # user 1
    [88, 70, 50, 60, 95],   # user 2
    [50, 60, 75, 80, 65],   # user 3
    [95, 90, 98, 87, 100],  # user 4
    [60, 65, 70, 55, 75]    # user 5
])

# the average score per user
user_average = np.mean(users,axis=1)
print(f"The average score of the each user is: \n{user_average}\n")

# the top 2 performers
top2_indices = np.argsort(user_average)[-2:]
top2_users = users[top2_indices]

print(f"The top 2 users are \n{top2_users}\n")

# mean of the top 2 performer
mean_top2 = users[top2_indices].mean()
print(f"mean of the top 2 performer is: {mean_top2}\n")

# the weakest performing user
weak_user = np.argmin(user_average)
print(f"The Weakest performing user is: {weak_user + 1} with average score of {user_average[weak_user]:.2f}\n") 

# Replace the lowest average with the mean of the top 2 performers
users_modify = users.copy()
users_modify[weak_user] = [mean_top2] * users.shape[1]
print(f"Updated scores after boosting weakest performer:\n{users_modify}")

The average score of the each user is: 
[81.  72.6 66.  94.  65. ]

The top 2 users are 
[[ 70  60  90 100  85]
 [ 95  90  98  87 100]]

mean of the top 2 performer is: 87.5

The Weakest performing user is: 5 with average score of 65.00

Updated scores after boosting weakest performer:
[[ 70  60  90 100  85]
 [ 88  70  50  60  95]
 [ 50  60  75  80  65]
 [ 95  90  98  87 100]
 [ 87  87  87  87  87]]


Performance Analyzer Module

Scenario:
You’re building a "Team Performance Analyzer" for an organization.

import numpy as np

team_scores = np.array([
    [70, 80, 90, 85, 88],  # Team A
    [60, 65, 58, 62, 66],  # Team B
    [90, 92, 88, 95, 94],  # Team C
    [45, 55, 60, 52, 50],  # Team D
])

# 1. Find average, std, and variance for each team
# 2. Identify the most consistent team (lowest std)
# 3. Replace lowest performer’s score with team average
# 4. Calculate the team with highest mean score

In [14]:
import numpy as np

team_scores = np.array([
    [70, 80, 90, 85, 88],  # Team A
    [60, 65, 58, 62, 66],  # Team B
    [90, 92, 88, 95, 94],  # Team C
    [45, 55, 60, 52, 50],  # Team D
])

# average, std, and variance for each team
team_avg = team_scores.mean(axis=1)
team_std = team_scores.std(axis=1)
team_var = team_scores.var(axis=1)

team_avg_rounded = np.round(team_avg, 2)
team_std_rounded = np.round(team_std, 2)
team_var_rounded = np.round(team_var, 2)

print("Average score of each team is\n", team_avg_rounded, "\n")
print("Standard Deviation of each team is\n", team_std_rounded, "\n")
print("Variance of each team is\n", team_var_rounded, "\n")

# most consistent team (lowest std)
most_consistent = np.argmin(team_std)

for i in range(len(team_std)):
    if i == most_consistent:
        print(f"Team {i + 1} is the most consistent with Standard Deviation of {team_std[i]:.2f}\n")
        break

# replacing the lowest performer’s score with team average

team_scores_modify = team_scores.copy()

for i in range (team_scores_modify.shape[0]):
    min_index = np.argmin(team_scores_modify[i])
    team_scores_modify[i][min_index] = team_avg[i]
    
print(f"Scores after replacing lowest with average is \n {team_scores_modify} \n")

# the team with highest mean score
high_mean = np.argmax(team_avg)
for i in range(len(team_avg)):
    if i == high_mean:
        print(f"Team {i + 1} has the highest mean with mean value {team_avg[i]:.2f}\n")
        break

Average score of each team is
 [82.6 62.2 91.8 52.4] 

Standard Deviation of each team is
 [7.14 2.99 2.56 5.  ] 

Variance of each team is
 [51.04  8.96  6.56 25.04] 

Team 3 is the most consistent with Standard Deviation of 2.56

Scores after replacing lowest with average is 
 [[82 80 90 85 88]
 [60 65 62 62 66]
 [90 92 91 95 94]
 [52 55 60 52 50]] 

Team 3 has the highest mean with mean value 91.80



Mini Project: Recommendation Engine Base

Simulate: A matrix of 4 users and 5 products (ratings out of 10)

Normalize the data (optional)

Transpose it

Multiply with itself (dot product) to find item similarity

This is a building block for content-based recommender systems.

In [ ]:
import numpy as np

# Simulated rating matrix: 4 users × 5 products
ratings = np.array([
    [10, 8, 0, 4, 7],
    [6, 0, 7, 5, 3],
    [9, 9, 8, 0, 6],
    [0, 5, 4, 6, 0]
])

T = ratings.T
print(T)

print(ratings @ T)

[[10  6  9  0]
 [ 8  0  9  5]
 [ 0  7  8  4]
 [ 4  5  0  6]
 [ 7  3  6  0]]
[[229 101 204  64]
 [101 119 128  58]
 [204 128 262  77]
 [ 64  58  77  77]]
