Top Performer Dashboard

given an array of weekly productivity scores for 5 users:

Tasks:

Compute the average score per user

Identify the top 2 performers

Highlight the weakest performing user

Replace the lowest average with the mean of the top 2 performers

In [23]:
# Top Performer Dashboard
import numpy as np

users = np.array([
    [70, 60, 90, 100, 85],  # user 1
    [88, 70, 50, 60, 95],   # user 2
    [50, 60, 75, 80, 65],   # user 3
    [95, 90, 98, 87, 100],  # user 4
    [60, 65, 70, 55, 75]    # user 5
])

# the average score per user
user_average = np.mean(users,axis=1)
print(f"The average score of the each user is: \n{user_average}\n")

# the top 2 performers
top2_indices = np.argsort(user_average)[-2:]
top2_users = users[top2_indices]

print(f"The top 2 users are \n{top2_users}\n")

# mean of the top 2 performer
mean_top2 = users[top2_indices].mean()
print(f"mean of the top 2 performer is: {mean_top2}\n")

# the weakest performing user
weak_user = np.argmin(user_average)
print(f"The Weakest performing user is: {weak_user + 1} with average score of {user_average[weak_user]:.2f}\n") 

# Replace the lowest average with the mean of the top 2 performers
users_modify = users.copy()
users_modify[weak_user] = [mean_top2] * users.shape[1]
print(f"Updated scores after boosting weakest performer:\n{users_modify}")

The average score of the each user is: 
[81.  72.6 66.  94.  65. ]

The top 2 users are 
[[ 70  60  90 100  85]
 [ 95  90  98  87 100]]

mean of the top 2 performer is: 87.5

The Weakest performing user is: 5 with average score of 65.00

Updated scores after boosting weakest performer:
[[ 70  60  90 100  85]
 [ 88  70  50  60  95]
 [ 50  60  75  80  65]
 [ 95  90  98  87 100]
 [ 87  87  87  87  87]]
